
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Hapus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hapus.class.getName());

    /**
     * Creates new form Hapus
     */
    private int userId; // variabel untuk simpan user id
    private List<String> realPasswords = new ArrayList<>(); // simpan password asli
    private List<Integer> credentialIds = new ArrayList<>(); // simpan credential_id untuk update
    private javax.swing.JFrame previousPage; // simpan halaman sebelumnya

    public Hapus(int userId, JFrame previousPage) {
        this.previousPage = previousPage;
        this.userId = userId;
        initComponents();
        loadData();
    }
    public Hapus() {
        initComponents();
    }
    
    private void loadData() {
        realPasswords.clear();
        credentialIds.clear();
        
        // Ambil master key dari session Tampilan_utama
        byte[] hashedMasterKey = Tampilan_utama.currentHashedMasterKey;
        
        // Buat model tabel
        DefaultTableModel model = (DefaultTableModel) tabel_hapus.getModel();
        model.setRowCount(0); // kosongkan tabel dulu
        

        try {
            Connection conn = Database.getConnection();
            PreparedStatement pst = conn.prepareStatement(
                "SELECT credential_id, account, username, password, link, notes FROM credentials WHERE user_id = ?"
            );
            pst.setInt(1, userId);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int credentialId = rs.getInt("credential_id");
                String encAccount = rs.getString("account");
                String encUsername = rs.getString("username");
                String encPassword = rs.getString("password");
                String encLink = rs.getString("link");
                String encNotes = rs.getString("notes");

                // 🔓 Decrypt tiap field
                String account = encryption.decrypt(encAccount, hashedMasterKey);
                String username = encryption.decrypt(encUsername, hashedMasterKey);
                String password = encryption.decrypt(encPassword, hashedMasterKey);
                String link = encryption.decrypt(encLink, hashedMasterKey);
                String notes = encryption.decrypt(encNotes, hashedMasterKey);

                // simpan password asli
                realPasswords.add(password);
                credentialIds.add(credentialId);
                model.addRow(new Object[]{account, username, "******", link, notes});
                
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_hapus = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        input_hapus = new javax.swing.JTextField();
        tombol_hapus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 58, 138));
        jPanel2.setPreferredSize(new java.awt.Dimension(269, 53));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HAPUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        jPanel1.setBackground(new java.awt.Color(245, 249, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(269, 380));

        tabel_hapus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Akun", "Username", "Password", "Link", "Catatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_hapusMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_hapus);

        jLabel2.setText("Input Username : ");

        tombol_hapus.setBackground(new java.awt.Color(59, 130, 246));
        tombol_hapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tombol_hapus.setForeground(new java.awt.Color(255, 255, 255));
        tombol_hapus.setText("HAPUS");
        tombol_hapus.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tombol_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_hapusActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imh/back_1.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imh/icons8-menu-50 (1) (1).png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imh/home.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombol_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(input_hapus)
                        .addContainerGap())))
            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel12)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tombol_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 270, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void tombol_hapusActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String usernameInput = input_hapus.getText().trim();
        byte[] hashedMasterKey = Tampilan_utama.currentHashedMasterKey;
        
        // Konfirmasi sebelum hapus
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin \nmenghapus data dengan \nusername: " + usernameInput + "?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return; // user membatalkan
        }   
        try {
            Connection conn = Database.getConnection();

            PreparedStatement pst = conn.prepareStatement(
                "SELECT credential_id, username FROM credentials WHERE user_id=?"
            );
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();

            boolean found = false;
            int credentialIdToDelete = -1;

            while (rs.next()) {
                int credentialId = rs.getInt("credential_id");
                String encUsername = rs.getString("username");
                String username = encryption.decrypt(encUsername, hashedMasterKey);

                if (username.equals(usernameInput)) {
                    credentialIdToDelete = credentialId;
                    found = true;
                    break;
                }
            }

            if (found) {
                PreparedStatement pstDelete = conn.prepareStatement(
                    "DELETE FROM credentials WHERE credential_id=? AND user_id=?"
                );
                pstDelete.setInt(1, credentialIdToDelete);
                pstDelete.setInt(2, userId);
                int deleted = pstDelete.executeUpdate();

                if (deleted > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username tidak ditemukan.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }                                            

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {                                      
        previousPage.setVisible(true);
        this.dispose();
    }                                     

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {                                     
        Login cek = new Login(); 
        cek.setVisible(true);          // Menampilkan halaman register
        this.dispose();
    }                                    

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {                                      
        System.exit(0);
    }                                     

    private void tabel_hapusMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (evt.getClickCount() == 2) { // cek double-click
            int row = tabel_hapus.getSelectedRow();
            if (row != -1) {
                String account = (String) tabel_hapus.getValueAt(row, 0);
                String username = (String) tabel_hapus.getValueAt(row, 1);
                String password = realPasswords.get(row); // ambil password asli
                String link = (String) tabel_hapus.getValueAt(row, 3);
                String notes = (String) tabel_hapus.getValueAt(row, 4);

                // buka JFrame detail
                detail_tampilkan detail = new detail_tampilkan(this, userId, account, username, password, link, notes);
                detail.setVisible(true);
            }
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Hapus().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField input_hapus;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tabel_hapus;
    private javax.swing.JButton tombol_hapus;
    // End of variables declaration                   
}
